# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
        maxHttpPostSize: 2048000
    port: 80
# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver

